# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-08 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufactory',
            name='memo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='manufactory',
            name='support_num',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u652f\u6301\u7535\u8bdd'),
        ),
    ]
