# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-08 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20170308_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverUserName', models.CharField(max_length=32, verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d')),
                ('serverUserPasswd', models.CharField(max_length=32, verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8\xe7\x94\xa8\xe6\x88\xb7\xe5\xaf\x86\xe7\xa0\x81')),
                ('serverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Server')),
            ],
        ),
        migrations.AlterField(
            model_name='manufactory',
            name='manufactory',
            field=models.CharField(max_length=64, unique=True, verbose_name=b'Manufactory'),
        ),
        migrations.AlterField(
            model_name='manufactory',
            name='memo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name=b'Memo'),
        ),
        migrations.AlterField(
            model_name='manufactory',
            name='support_num',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=b'Support_phone'),
        ),
    ]
