# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 10:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_idc_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='idc',
            name='update_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 3, 15, 10, 28, 56, 204000), verbose_name='\u66f4\u65b0\u65f6\u95f4'),
            preserve_default=False,
        ),
    ]
