# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_idc_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='tags',
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[(b'Server', '\u670d\u52a1\u5668'), (b'Storage', '\u5b58\u50a8\u8bbe\u5907'), (b'Security', '\u5b89\u5168\u8bbe\u5907'), (b'Equipment', '\u673a\u623f\u8bbe\u5907'), (b'Switch', '\u4ea4\u6362\u673a'), (b'Router', '\u8def\u7531\u5668'), (b'Software', '\u8f6f\u4ef6\u8d44\u4ea7'), (b'Others', '\u5176\u5b83\u7c7b')], default=b'Server', max_length=64, verbose_name='\u8d44\u4ea7\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='\u8d44\u4ea7\u540d\u79f0'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
