# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-17 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20170315_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u673a\u67b6\u540d\u79f0')),
                ('cabinet', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field=b'idc', chained_model_field=b'idc', null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Cabinet', verbose_name='\u673a\u67dc')),
                ('idc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.IDC', verbose_name=b'IDC')),
            ],
            options={
                'verbose_name': '\u673a\u67b6',
                'verbose_name_plural': '\u673a\u67b6',
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.SmallIntegerField(choices=[(0, b'\xe5\x9c\xa8\xe7\xba\xbf'), (1, b'\xe5\xb7\xb2\xe4\xb8\x8b\xe7\xba\xbf'), (2, b'\xe6\x9c\xaa\xe7\x9f\xa5'), (3, b'\xe6\x95\x85\xe9\x9a\x9c'), (4, b'\xe5\xa4\x87\xe7\x94\xa8')], default=0, verbose_name='\u72b6\u6001'),
        ),
    ]
