# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-17 10:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20170317_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rack',
            name='cabinet',
        ),
        migrations.AddField(
            model_name='rack',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 3, 17, 10, 16, 17, 254000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rack',
            name='update_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 3, 17, 10, 16, 26, 279000), verbose_name='\u66f4\u65b0\u65f6\u95f4'),
            preserve_default=False,
        ),
    ]
