# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-17 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_auto_20170317_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
