# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-01 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0006_auto_20170314_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='auth_group',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100, unique=True, verbose_name='\u89d2\u8272\u540d\u79f0')),
                ('enable', models.BooleanField(default=True, verbose_name='\u662f\u5426\u542f\u7528')),
                ('explanation', models.TextField(verbose_name='\u89d2\u8272\u63cf\u8ff0')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('group_user', models.ManyToManyField(blank=True, to='User.User', verbose_name='\u6240\u5c5e\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u89d2\u8272\u7ba1\u7406',
                'verbose_name_plural': '\u89d2\u8272\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='user_auth_cmdb',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('select_host', models.BooleanField(default=False, verbose_name='\u67e5\u770b\u8d44\u4ea7')),
                ('edit_host', models.BooleanField(default=False, verbose_name='\u4fee\u6539\u8d44\u4ea7')),
                ('update_host', models.BooleanField(default=False, verbose_name='\u66f4\u65b0\u8d44\u4ea7')),
                ('add_host', models.BooleanField(default=False, verbose_name='\u6dfb\u52a0\u4e3b\u673a')),
                ('bat_add_host', models.BooleanField(default=False, verbose_name='\u6279\u91cf\u6dfb\u52a0')),
                ('delete_host', models.BooleanField(default=False, verbose_name='\u5220\u9664\u8d44\u4ea7')),
                ('add_line_auth', models.BooleanField(default=False, verbose_name='\u4ea7\u54c1\u7ebf\u7ba1\u7406')),
                ('auth_project', models.BooleanField(default=False, verbose_name='\u81ea\u52a8\u5316\u53d1\u5e03')),
                ('auth_highstate', models.BooleanField(default=False, verbose_name='\u81ea\u52a8\u5316\u90e8\u7f72')),
                ('add_user', models.BooleanField(default=False, verbose_name='\u6dfb\u52a0\u7528\u6237')),
                ('edit_user', models.BooleanField(default=False, verbose_name='\u4fee\u6539\u7528\u6237')),
                ('edit_pass', models.BooleanField(default=False, verbose_name='\u4fee\u6539\u5bc6\u7801')),
                ('delete_user', models.BooleanField(default=False, verbose_name='\u5220\u9664\u7528\u6237')),
                ('add_department', models.BooleanField(default=False, verbose_name='\u90e8\u95e8\u7ba1\u7406')),
                ('select_idc', models.BooleanField(default=False, verbose_name='\u67e5\u770b\u673a\u623f')),
                ('add_idc', models.BooleanField(default=False, verbose_name='\u6dfb\u52a0\u673a\u623f')),
                ('edit_idc', models.BooleanField(default=False, verbose_name='\u4fee\u6539\u673a\u623f')),
                ('del_idc', models.BooleanField(default=False, verbose_name='\u5220\u9664\u673a\u623f')),
                ('setup_system', models.BooleanField(default=False, verbose_name='\u5b89\u88c5\u7cfb\u7edf')),
                ('upload_system', models.BooleanField(default=False, verbose_name='\u4e3b\u673a\u4e0a\u62a5')),
                ('salt_keys', models.BooleanField(default=False, verbose_name='\u4e3b\u673a\u4e0a\u62a5')),
                ('project_auth', models.BooleanField(default=False, verbose_name='\u9879\u76ee\u5217\u8868')),
                ('add_project', models.BooleanField(default=False, verbose_name='\u6dfb\u52a0\u9879\u76ee')),
                ('edit_project', models.BooleanField(default=False, verbose_name='\u4fee\u6539\u9879\u76ee')),
                ('delete_project', models.BooleanField(default=False, verbose_name='\u5220\u9664\u9879\u76ee')),
                ('auth_log', models.BooleanField(default=False, verbose_name='salt\u6267\u884c\u8bb0\u5f55')),
                ('cmdb_log', models.BooleanField(default=False, verbose_name='\u8d44\u4ea7\u64cd\u4f5c\u8bb0\u5f55')),
                ('server_audit', models.BooleanField(default=False, verbose_name='\u670d\u52a1\u5668\u64cd\u4f5c\u8bb0\u5f55')),
                ('group_name', models.ForeignKey(help_text='\u6dfb\u52a0\u89d2\u8272\u7ec4\u6743\u9650', on_delete=django.db.models.deletion.CASCADE, to='cmdb_auth.auth_group', verbose_name='\u6240\u5c5e\u89d2\u8272')),
            ],
            options={
                'verbose_name': '\u6743\u9650\u7ba1\u7406',
                'verbose_name_plural': '\u6743\u9650\u7ba1\u7406',
            },
        ),
    ]
