# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-01 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth_group',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='user_auth_cmdb',
            name='uuid',
        ),
        migrations.AddField(
            model_name='auth_group',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_auth_cmdb',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
