# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-05 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_auth', '0002_auto_20170401_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_auth_cmdb',
            name='salt_keys',
            field=models.BooleanField(default=False, verbose_name='\u6279\u91cf\u7ba1\u7406'),
        ),
    ]
