# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-22 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZabbixMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('ip', models.CharField(max_length=20)),
                ('ping', models.IntegerField(null=True)),
                ('diskc', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('diskd', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
