# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20170324_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='template_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Templates', verbose_name='\u6a21\u677fid'),
        ),
    ]
