# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20170324_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryusage',
            name='free',
            field=models.CharField(default=1, max_length=16, verbose_name='\u7a7a\u95f2\u5185\u5b58'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memoryusage',
            name='percent',
            field=models.CharField(default=1, max_length=16, verbose_name='\u5185\u5b58\u4f7f\u7528'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memoryusage',
            name='total',
            field=models.CharField(default=1, max_length=16, verbose_name='\u603b\u5185\u5b58'),
            preserve_default=False,
        ),
    ]
