# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-07 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0016_auto_20170317_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=100, verbose_name='Salt\u547d\u4ee4')),
                ('doc', models.TextField(blank=True, max_length=1000, verbose_name='\u5e2e\u52a9\u6587\u6863')),
            ],
            options={
                'verbose_name': 'Salt\u547d\u4ee4',
                'verbose_name_plural': 'Salt\u547d\u4ee4\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Minions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minion', models.CharField(max_length=50, verbose_name='\u5ba2\u6237\u7aef')),
                ('grains', models.TextField(blank=True, max_length=500, verbose_name='Grains\u4fe1\u606f')),
                ('pillar', models.TextField(blank=True, max_length=500, verbose_name='Pillar\u4fe1\u606f')),
                ('status', models.CharField(choices=[('Unknown', 'Unknown'), ('Accepted', 'Accepted'), ('Denied', 'Denied'), ('Unaccepted', 'Unaccepted'), ('Rejected', 'Rejected')], default='Unknown', max_length=20, verbose_name='\u5728\u7ebf\u72b6\u6001')),
            ],
            options={
                'verbose_name': 'Salt\u5ba2\u6237\u7aef',
                'verbose_name_plural': 'Salt\u5ba2\u6237\u7aef\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(default='execution', max_length=20, verbose_name='Salt\u6a21\u5757\u7c7b\u578b')),
                ('name', models.CharField(max_length=20, verbose_name='Salt\u6a21\u5757\u540d\u79f0')),
            ],
            options={
                'verbose_name': 'Salt\u6a21\u5757',
                'verbose_name_plural': 'Salt\u6a21\u5757\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=20, verbose_name='\u6267\u884c\u65b9\u5f0f')),
                ('fun', models.CharField(max_length=50, verbose_name='\u547d\u4ee4')),
                ('arg', models.CharField(blank=True, max_length=255, verbose_name='\u53c2\u6570')),
                ('tgt_type', models.CharField(max_length=20, verbose_name='\u76ee\u6807\u7c7b\u578b')),
                ('jid', models.CharField(blank=True, max_length=50, verbose_name='\u4efb\u52a1\u53f7')),
                ('minions', models.CharField(blank=True, max_length=500, verbose_name='\u76ee\u6807\u4e3b\u673a')),
                ('result', models.TextField(blank=True, verbose_name='\u8fd4\u56de\u7ed3\u679c')),
                ('user', models.CharField(max_length=50, verbose_name='\u64cd\u4f5c\u7528\u6237')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='\u6267\u884c\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u547d\u4ee4\u8fd4\u56de\u7ed3\u679c',
                'verbose_name_plural': '\u547d\u4ee4\u8fd4\u56de\u7ed3\u679c',
            },
        ),
        migrations.CreateModel(
            name='SaltServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=100, verbose_name='URL\u5730\u5740')),
                ('username', models.CharField(max_length=50, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=50, verbose_name='\u5bc6\u7801')),
                ('role', models.CharField(choices=[('Master', 'Master'), ('Backend', 'Backend')], default='Master', max_length=20, verbose_name='\u89d2\u8272')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.IDC', verbose_name='\u6240\u5c5e\u673a\u623f')),
            ],
            options={
                'verbose_name': 'Salt\u670d\u52a1\u5668',
                'verbose_name_plural': 'Salt\u670d\u52a1\u5668\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=20, verbose_name='\u6267\u884c\u65b9\u5f0f')),
                ('fun', models.CharField(max_length=50, verbose_name='\u547d\u4ee4')),
                ('arg', models.CharField(blank=True, max_length=255, verbose_name='\u53c2\u6570')),
                ('tgt_type', models.CharField(max_length=20, verbose_name='\u76ee\u6807\u7c7b\u578b')),
                ('jid', models.CharField(blank=True, max_length=50, verbose_name='\u4efb\u52a1\u53f7')),
                ('minions', models.CharField(blank=True, max_length=500, verbose_name='\u76ee\u6807\u4e3b\u673a')),
                ('result', models.TextField(blank=True, verbose_name='\u8fd4\u56de\u7ed3\u679c')),
                ('user', models.CharField(max_length=50, verbose_name='\u64cd\u4f5c\u7528\u6237')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='\u6267\u884c\u65f6\u95f4')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salt.SaltServer', verbose_name='\u6240\u5c5eSalt\u670d\u52a1\u5668')),
            ],
            options={
                'verbose_name': '\u90e8\u7f72\u7ed3\u679c',
                'verbose_name_plural': '\u90e8\u7f72\u7ed3\u679c',
            },
        ),
        migrations.AddField(
            model_name='result',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salt.SaltServer', verbose_name='\u6240\u5c5eSalt\u670d\u52a1\u5668'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set([('client', 'name')]),
        ),
        migrations.AddField(
            model_name='minions',
            name='salt_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salt.SaltServer', verbose_name='\u6240\u5c5eSalt\u670d\u52a1\u5668'),
        ),
        migrations.AddField(
            model_name='command',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salt.Module', verbose_name='\u6240\u5c5e\u6a21\u5757'),
        ),
        migrations.AlterUniqueTogether(
            name='minions',
            unique_together=set([('minion', 'salt_server')]),
        ),
        migrations.AlterUniqueTogether(
            name='command',
            unique_together=set([('module', 'cmd')]),
        ),
    ]
