# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='jid',
            field=models.CharField(blank=True, max_length=64, verbose_name='\u4efb\u52a1\u53f7'),
        ),
    ]
