# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-24 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Department',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'IDC',
                'verbose_name_plural': 'IDC',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Administrator'), ('superuser', 'SuperUser'), ('guest', 'Guest')], max_length=64, verbose_name='PermissionName')),
            ],
            options={
                'verbose_name': 'UserPermission',
                'verbose_name_plural': 'UserPermission',
            },
        ),
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='GroupName')),
            ],
            options={
                'verbose_name': 'UserGroup',
                'verbose_name_plural': 'UserGroup',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='Username')),
                ('password', models.CharField(max_length=64, verbose_name='Password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=28, null=True, verbose_name='Phone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image/userPhoto', verbose_name='Head')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Department', verbose_name='Department')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.IDC', verbose_name='IDC')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.UserGroups', verbose_name='UserGroup')),
                ('user_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Permission', verbose_name='UserPermission')),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfile',
            },
        ),
    ]
