# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-13 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20170304_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='comment',
            field=models.CharField(default=1, max_length=128, verbose_name='\u6743\u9650\u8bf4\u660e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='method',
            name='name_cn',
            field=models.CharField(default=1, max_length=32, verbose_name='\u6743\u9650\u4e2d\u6587\u540d\u79f0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='method',
            name='url',
            field=models.CharField(default=1, max_length=32, verbose_name='\u6743\u9650url\u8def\u5f84'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_lock',
            field=models.IntegerField(default=0, verbose_name='\u7528\u6237\u9501\u5b9a'),
        ),
        migrations.AddField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u7528\u6237\u6ce8\u518c\u65e5\u671f'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u4e0a\u6b21\u767b\u5f55\u65e5\u671f'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.CharField(default=1, max_length=32, verbose_name='\u7528\u6237\u8d4b\u4e88\u7684\u89d2\u8272'),
            preserve_default=False,
        ),
    ]
