# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-13 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20170313_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(verbose_name='\u7ec4id')),
                ('method_id', models.IntegerField(verbose_name='\u6743\u9650id')),
                ('delete_flag', models.CharField(max_length=4, verbose_name='\u5220\u9664\u6807\u5fd7')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='\u7528\u6237id')),
                ('group_id', models.IntegerField(verbose_name='\u7ec4id')),
                ('delete_flag', models.CharField(max_length=4, verbose_name='\u5220\u9664\u6807\u5fd7')),
            ],
        ),
        migrations.CreateModel(
            name='UserMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='\u7528\u6237id')),
                ('method_id', models.IntegerField(verbose_name='\u6743\u9650id')),
                ('delete_flag', models.CharField(max_length=4, verbose_name='\u5220\u9664\u6807\u5fd7')),
            ],
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '\u7ec4\u4fe1\u606f', 'verbose_name_plural': '\u7ec4\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='method',
            options={'verbose_name': '\u6743\u9650\u4fe1\u606f', 'verbose_name_plural': '\u6743\u9650\u4fe1\u606f'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role_id',
        ),
        migrations.AddField(
            model_name='group',
            name='comment',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7ec4\u4fe1\u606f'),
        ),
        migrations.AddField(
            model_name='group',
            name='delete_flag',
            field=models.CharField(default='N', max_length=4, verbose_name='\u5220\u9664\u6807\u5fd7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='method',
            name='delete_flag',
            field=models.CharField(default='N', max_length=4, verbose_name='\u5220\u9664\u6807\u5fd7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='delete_flag',
            field=models.CharField(default='N', max_length=4, verbose_name='\u5220\u9664\u6807\u5fd7'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='method',
            name='comment',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u6743\u9650\u8bf4\u660e'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_lock',
            field=models.CharField(max_length=4, verbose_name='\u7528\u6237\u9501\u5b9a\u72b6\u6001'),
        ),
    ]
