# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-14 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20170313_1654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupMethod',
            new_name='GroupPermission',
        ),
        migrations.RenameModel(
            old_name='Method',
            new_name='Permission',
        ),
        migrations.RenameModel(
            old_name='UserMethod',
            new_name='UserPermission',
        ),
        migrations.RenameField(
            model_name='grouppermission',
            old_name='method_id',
            new_name='permission_id',
        ),
        migrations.RenameField(
            model_name='userpermission',
            old_name='method_id',
            new_name='permission_id',
        ),
    ]
